### ISSUE TITLE
Release 0.10

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#107]
In GitLab by @azriel91 on Mar 29, 2019, 09:11

Tasks:

* [x] Publish binaries: [itch.io/will](https://azriel91.itch.io/will)
* [x] Blog - [azriel.im/will](http://www.azriel.im/will/) ([post](https://azriel.im/will/2019/03/29/dash/))
* Notify people

    - [x] [Users forum](https://users.rust-lang.org) ([what's everyone working on this week](https://users.rust-lang.org/t/whats-everyone-working-on-this-week-13-2019/26631/10))
    - [x] Amethyst - Discord
