### ISSUE TITLE
Release Housekeeping

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#121]
In GitLab by @azriel91 on May 5, 2019, 18:13

Tasks:

* [x] ion-shell MIT License in relevant source files.
* [x] EULA for binary.
* [x] Last minute maintenance (e.g. clippy).
* [x] Ship `default/heat` with release.
