### ISSUE TITLE
Game: Play State with single character

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#13]
In GitLab by @azriel91 on Mar 3, 2018, 09:00

Covers:

* [x] **\[Load assets\]** Images
* [x] **\[Define entities\]** Characters
* [x] **\[Load assets\]** Character Data (#13)

Related:

* Rendering sprites in amethyst: [amethyst/pull/638](https://github.com/amethyst/amethyst/pull/638)

Moved "**\[Load assets\]** Controls" into next milestone (#32).

**Comment by azriel91** [comment]
In GitLab by @azriel91 on Apr 23, 2018, 07:32

**TODO:**

* [x] Rebase the Amethyst animation branch.
* [x] Update `RobotState`s to pass through `Intercept`s so that tests work again.
* [ ] Remove clone on game config, and create entities with collected components.
* [ ] Refactor `object_loader`: extract into smaller logic containers.
* [ ] Write automated tests for each of the loading bits.
