### ISSUE TITLE
Release 0.11.0

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#130]
In GitLab by @azriel91 on May 22, 2019, 17:17

Tasks:

* [x] Publish binaries: [itch.io/will](https://azriel91.itch.io/will)
* [x] Blog - [azriel.im/will](http://www.azriel.im/will/) ([post](https://azriel.im/will/2019/05/24/into-the-wild/))
* Notify people

    - [x] [Users forum](https://users.rust-lang.org) ([Will - 2.5D moddable action game](https://users.rust-lang.org/t/will-2-5d-moddable-action-game/28537))
    - Purple-Faced Folk - fb messenger
    - [x] Cheese Tea - fb messenger
    - [x] Amethyst - Discord
