### ISSUE TITLE
Release 0.13

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#152]
In GitLab by @azriel91 on Aug 12, 2019, 22:13

Tasks:

* [x] Publish binaries: [itch.io/will](https://azriel91.itch.io/will)
* [x] Blog - [azriel.im/will](http://www.azriel.im/will/) ([post](https://azriel.im/will/2019/08/16/charging-up/))
* Notify people

    - [x] [Users forum](https://users.rust-lang.org) ([Will - 2.5D moddable action game](https://users.rust-lang.org/t/will-2-5d-moddable-action-game/28537/5))
    - [x] Purple-Faced Folk - fb messenger / discord
    - [x] Cheese Tea - fb messenger
    - [x] Amethyst - Discord
