### ISSUE TITLE
Release 0.14

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#169]
In GitLab by @azriel91 on Sep 26, 2019, 19:11

Tasks:

* [x] Publish binaries: [itch.io/will](https://azriel91.itch.io/will)
* [x] Blog - [azriel.im/will](http://www.azriel.im/will/) ([post](https://azriel.im/will/2019/09/27/focus/))
* Notify people

    - [x] [Users forum](https://users.rust-lang.org) ([Will - 2.5D moddable action game](https://users.rust-lang.org/t/will-2-5d-moddable-action-game/28537/6))
    - [x] Purple-Faced Folk - fb messenger / discord
    - [x] Cheese Tea - fb messenger
    - [x] Amethyst - Discord
