### ISSUE TITLE
Map Selection UI

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#176]
In GitLab by @azriel91 on Oct 22, 2019, 17:09

**Tasks:**

* [x] Define configuration format.
* [x] Display selected map.
* [x] Send `MapSelectionEvent`s on input event / widget sequence transition event.
* [x] Separate `AssetDisplayCell` implementations per asset type.
* [x] Create `ScaleInit` component that changes the `Transform::scale` of entities.
* [x] Weird bug

    After entering game play, then back to character selection, then to map selection, then back to character selection,

    character preview entities are spawned but not deleted.

    Turns out the `CswMain` entity was being found as the `AssetSelectionParent` entity to delete preview entities from, but that wasn't the entity that is the actual asset selection parent. Changed the logic to use `AssetSelectionHighlightMain` entity as the `AssetSelectionParent`.

* [x] Rename `CswPreviewSpawnSystem` to `ApwPreviewSpawnSystem`
* [x] Type parameterize `ApwPreviewSpawnSystem` to spawn entities for either `Character`s or `Map`s
* [x] Read `Dimensions` for asset preview widget, and scale preview entity based on that.
