### ISSUE TITLE
0.1 Release Binaries

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#18]
In GitLab by @azriel91 on Mar 8, 2018, 23:39

* [x] Builds + Tests pass on Ubuntu - X11
* [x] Builds + Tests pass on Windows
* ~~Cross compile works in CI~~ Not required: now compiling natively on Linux and Windows OSes
* [x] Publishes to itch.io
