### ISSUE TITLE
Release 0.17.0

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#193]
In GitLab by @azriel91 on Jan 29, 2020, 14:55

Tasks:

* [x] Publish binaries: [itch.io/will](https://azriel91.itch.io/will)
* [x] Blog - [azriel.im/will](http://www.azriel.im/will/) ([post](https://azriel.im/will/2020/01/31/i-choose-ui/))
* Notify people

    - [x] [Users forum](https://users.rust-lang.org) ([Will - 2.5D moddable action game](https://users.rust-lang.org/t/will-2-5d-moddable-action-game/28537/9))
    - [x] Purple-Faced Folk - fb messenger / discord
    - [x] Cheese Tea - fb messenger
    - [x] Amethyst - Discord
