### ISSUE TITLE
Release 0.18.0

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#208]
In GitLab by @azriel91 on Mar 12, 2020, 18:45

Tasks:

* [x] Publish binaries: [itch.io/will](https://azriel91.itch.io/will)
* [x] Blog - [azriel.im/will](https://www.azriel.im/will/) ([post](https://azriel.im/will/2020/03/13/join-me/))
* Notify people

    - [x] [Users forum](https://users.rust-lang.org) ([Will - 2.5D moddable action game](https://users.rust-lang.org/t/will-2-5d-moddable-action-game/28537/11))
    - [x] Purple-Faced Folk - fb messenger / discord
    - [x] Cheese Tea - fb messenger
    - [x] Amethyst - Discord
    - [x] (others)
