### ISSUE TITLE
Release 0.19.0

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#224]
Tasks:

* [x] Publish binaries: [itch.io/will](https://azriel91.itch.io/will)
* [x] Blog - [azriel.im/will](https://azriel.im/will/) ([post](https://azriel.im/will/2020/04/24/browsers-assemble/))
* Notify people

    - [x] [Users forum](https://users.rust-lang.org) ([Will - 2.5D moddable action game](https://users.rust-lang.org/t/will-2-5d-moddable-action-game/28537))
    - [x] Discord
    - [x] Reddit -- [r/rust_gamedev](https://www.reddit.com/r/rust_gamedev/)
    - [x] Twitter
    - [x] Facebook
