### ISSUE TITLE
Load Keyboard Controls for players

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#32]
In GitLab by @azriel91 on Apr 26, 2018, 15:05

**Covers:**

* [x] **\[Load assets\]** Controls

**Tasks:**

* ~~Define Player~~ not required for this feature.
* [x] Define Controls
* [x] Map player controller to entity:
    - `CharacterEntityControl`
    - `PlayerAxisControl`
    - `PlayerActionControl`
* [x] System to change entity's sequence based on control input buffer and current sequence's state (!37)
    - `CharacterInputUpdateSystem`
    - `CharacterSequenceHandler`

Result:

* Controls are loaded and mapped to players.
* Players control their active entity.

Notes:

* `@torkleyy` mentioned [machinae](https://github.com/rustgd/machinae) for state management for objects.

**Comment by azriel91** [comment]
In GitLab by @azriel91 on May 3, 2018, 09:48

**TODO:**

* `CharacterInputUpdateSystem` can read `InputHandler<_, _>`, but needs the character definition to update the character entities.
* `Entity` needs a reference to its corresponding object definition, e.g. characters need to reference`CharacterDefinition`.
* Since `Entity` objects are created from `Object`s, perhaps update that to store a reference to the `ObjectDefinition`, or Character entities should have `Handle<CharacterDefinition>`.
* `ObjectLoader` needs to be updated to do this.
