### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#85]
In GitLab by @azriel91 on Nov 20, 2018, 19:12

Tasks:

* [x] Publish binaries: [itch.io/will](https://azriel91.itch.io/will)
* [x] Blog - [azriel.im/will](http://www.azriel.im/will/)
* [x] Notify people

    - [x] [Users forum](https://users.rust-lang.org) (what's everyone working on this week)
